---
version: '3.3'
services:
    application:
        image: nuetoban/crocodile:latest
        env_file: .env
        restart: on-failure
        depends_on:
            - postgresql
    postgresql:
        image: postgres:alpine
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
    redis:
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        image: 'bitnami/redis:latest'
        ports:
            - 6379:6379
